/**
 * Banco de 100 frases para práctica de mecanografía profesional.
 * Incluye: Mayúsculas, tildes, comas, puntos, interrogaciones y exclamaciones.
 */
const listaFrases = [
    "¿Sabías que la práctica diaria es el único camino al éxito?",
    "¡Cuidado con los errores, es mejor ir despacio y seguro!",
    "La tecnología avanza rápido, pero escribir bien es una habilidad eterna.",
    "El teclado español incluye la letra ñ, un símbolo único de nuestra lengua.",
    "¿Te gustaría aprender a programar aplicaciones móviles este año?",
    "¡Qué alegría verte progresar tan rápido con las tildes!",
    "Mañana iremos al parque, después a la biblioteca y finalmente a cenar.",
    "El sol brilla con fuerza hoy; sin embargo, prefiero quedarme estudiando.",
    "¿Dónde están las llaves del coche que dejé sobre la mesa de madera?",
    "¡Increíble! Has superado tu récord de palabras por minuto.",
    "La educación es el arma más poderosa para cambiar el mundo entero.",
    "¿Podrías decirme qué hora es, por favor?",
    "En un lugar de la Mancha, de cuyo nombre no quiero acordarme...",
    "¡Ánimo! Cada pulsación te acerca más a la maestría técnica.",
    "La música clásica ayuda a concentrarse mientras se escribe código.",
    "¿Prefieres el café con leche o prefieres un té verde bien caliente?",
    "Ayer compré manzanas, peras, limones y un poco de perejil fresco.",
    "¡Atención! El sistema detectó un error en la línea número diez.",
    "El éxito consiste en ir de fracaso en fracaso sin perder el entusiasmo.",
    "¿Cuál es tu lenguaje de programación favorito para trabajar?",
    "La paciencia es amarga, pero sus frutos son siempre muy dulces.",
    "¡No te rindas nunca, aunque el camino parezca difícil al principio!",
    "Hacer ejercicio físico es vital para mantener la salud mental y corporal.",
    "¿Has visitado alguna vez la ciudad de Madrid durante la primavera?",
    "El gato saltó por la ventana, corrió por el jardín y se escondió.",
    "¡Magnífico trabajo el que has realizado con este proyecto!",
    "La lectura abre puertas que nunca imaginaste que existían.",
    "¿Quién fue el autor de aquella famosa novela histórica?",
    "Siempre parece imposible hasta que finalmente se logra hacer.",
    "¡Felicidades por completar este nivel de dificultad avanzada!",
    "La lluvia caía suavemente sobre los tejados de la ciudad dormida.",
    "¿Cuántos idiomas hablas con fluidez en tu entorno laboral?",
    "La programación funcional es un paradigma muy interesante de estudiar.",
    "¡Socorro! Se ha caído el servidor principal de la oficina.",
    "Estudiar gramática es importante para escribir mensajes claros.",
    "¿Por qué decidiste empezar este curso de mecanografía hoy mismo?",
    "El tiempo vuela cuando te diviertes haciendo lo que más te gusta.",
    "¡Vaya sorpresa me llevé al ver el resultado del examen!",
    "La inteligencia artificial transformará la sociedad en pocos años.",
    "¿Es posible viajar a la Luna en un cohete comercial?",
    "Nuestra mayor debilidad reside en renunciar antes de tiempo.",
    "¡Silencio! Los estudiantes están realizando una prueba importante.",
    "Me gusta viajar por el mundo, conocer gente y probar comida nueva.",
    "¿Cuál es el océano más grande de todo el planeta Tierra?",
    "La constancia vence lo que la dicha no alcanza jamás.",
    "¡Cuidado, el café está muy caliente y podrías quemarte!",
    "El desarrollo web requiere conocer HTML, CSS y JavaScript.",
    "¿Crees que la robótica reemplazará muchos empleos actuales?",
    "Un pequeño paso para el hombre, pero un gran salto para la humanidad.",
    "¡Excelente! Has escrito esa frase sin cometer ni un solo error.",
    "El perro de San Roque no tiene rabo porque Ramón se lo ha cortado.",
    "¿Cuándo fue la última vez que fuiste al cine a ver una película?",
    "La creatividad es la inteligencia divirtiéndose, decía un genio.",
    "¡Qué paisaje tan bonito se ve desde la cima de esta montaña!",
    "Caminar treinta minutos al día mejora mucho la circulación sanguínea.",
    "¿Qué componentes necesita una computadora para funcionar bien?",
    "La ambición es el camino al éxito, la tenacidad es el vehículo.",
    "¡Rápido! El tren está a punto de salir de la estación central.",
    "Escribir código limpio es una muestra de respeto hacia tus compañeros.",
    "¿Cómo se llama el proceso de convertir agua en vapor?",
    "La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.",
    "¡Bravo! Tu precisión ha subido un cinco por ciento esta sesión.",
    "El archipiélago de las Canarias tiene un clima subtropical envidiable.",
    "¿Te gusta más el diseño gráfico o el desarrollo de software?",
    "La honestidad es el primer capítulo del libro de la sabiduría.",
    "¡Por favor, cierra la puerta al salir de la habitación!",
    "El conocimiento se comparte, el talento se cultiva con esfuerzo.",
    "¿Quién descubrió la ley de la gravedad universal?",
    "Lo único que sé es que no sé nada, afirmó el filósofo griego.",
    "¡Qué calor hace en esta zona durante los meses de verano!",
    "La práctica del yoga reduce el estrés y mejora la flexibilidad.",
    "¿Es necesario instalar una actualización de seguridad ahora?",
    "La imaginación es más importante que el conocimiento mismo.",
    "¡Mira hacia arriba y observa las estrellas en la noche despejada!",
    "El aprendizaje es un tesoro que seguirá a su dueño a todas partes.",
    "¿Cuánto cuesta el billete de avión para ir a Buenos Aires?",
    "La innovación distingue a los líderes de los seguidores.",
    "¡Escucha con atención lo que tengo que decirte sobre el proyecto!",
    "Las redes sociales tienen ventajas y desventajas muy claras.",
    "¿Cuál es la capital de Francia y qué monumentos famosos tiene?",
    "El que busca la verdad corre el riesgo de encontrarla.",
    "¡Estupendo! Has terminado todas las frases de este bloque.",
    "La energía solar es una fuente renovable y muy limpia.",
    "¿Qué harías si ganaras el premio mayor de la lotería nacional?",
    "Solo sé que cada día aprendo algo nuevo y fascinante.",
    "¡No olvides guardar los cambios antes de cerrar el editor!",
    "La montaña rusa del parque de atracciones es muy emocionante.",
    "¿Cuál es el significado de la palabra resiliencia en psicología?",
    "La libertad consiste en ser dueños de nuestra propia vida.",
    "¡Rápido, trae el botiquín de primeros auxilios que está en la cocina!",
    "El teclado es la herramienta principal de un escritor moderno.",
    "¿Has probado alguna vez la paella valenciana tradicional?",
    "La vida no se mide por las veces que respiras, sino por los momentos.",
    "¡Qué alegría me da saber que estás progresando tanto!",
    "La curiosidad es el motor que impulsa el descubrimiento científico.",
    "¿Cuál es tu película favorita de todos los tiempos y por qué?",
    "Escribir es una forma de terapia para muchas personas hoy en día.",
    "¡Buen trabajo! Has mantenido una velocidad constante todo el tiempo.",
    "La galaxia en la que vivimos se llama la Vía Láctea.",
    "¿Estás listo para empezar el siguiente nivel de dificultad?"
];